### PR TITLE
Handle empty 204 response without crashing

### LINKED ISSUE #37: Unexpected end of JSON input on 204 response
Hi there,

I seem to be getting an error from the `phin` library when an API returns a `204` status code which indicates that the response has no content. This looks like it is due to the `parse: "json"` option which tries to parse `null` instead of ignoring it. I will take a look at the source and see if it's an easy fix but just raising this issue for visibility

### PR DESCRIPTION
**Pull request by cdimitroulas**
Closes #37 

I was unable to find a script to generate a new minified file, what tool are you normally using to achieve this?

Otherwise, this PR adds a check for when `res.statusCode === 204` to avoid trying to call `res.json()` as this throws an error. Instead we resolve with an empty object (`{}`).

Once the minified file is regenerated this PR is good to go subject to any changes you suggest of course :)

### CODE REVIEW

**Comment by cdimitroulas** [comment]
hey @ethanent have you had a chance to look at this? :)

**Comment by wzhouwzhou** [comment]
It seems that there are merge conflicts. Any update on their resolutions?

-William

**Comment by cdimitroulas** [comment]
I can look at resolving those if I also get an answer to my question in the first comment :)

**Comment by wzhouwzhou** [comment]
It doesn't seem that the minified file is pertinent to this specific pull or your ability to resolve conflicts. So long as the maintainer/owner has access to both run the minification process and push relevant files to npm, those files should stay off git.

That being said, perhaps the repository is relying on jsdelivr or other such services to serve minified files from an outside cdn. In such a case, it would make sense not to have a minification script in the repository at all. Otherwise, the job of minifying the file falls back onto the repository owner.

@ethanent, any thoughts on these changes, other than inconsistent indentation/EOF?

-William

"Let him that would move the world first move himself." - Socrates

**Comment by cdimitroulas** [comment]
@wzhouwzhou I have resolved the conflicts now.

**Comment by wzhouwzhou** [comment]
Hey @ethanent, what do you think? The conflicts have been resolved and you've been requested for PR review.

-William

**Comment by ethanent** [comment]
Hi there! Thanks for the PR. Made some minor corrections as well as one more significant change -- it seems more reasonable to me to return `null` rather than `{}` when a 204 is received. What is your reasoning for choosing `{}`?

**Comment by cdimitroulas** [comment]
Returning `null` makes more sense, thanks for your improvement :+1:

**Comment by mariannefeng** [comment]
@ethanent any updates on this PR? I am seeing the phin client configured with `parse: json` error out for 204 responses as well

**Comment by cdimitroulas** [comment]
@ethanent pinging you to take a look at this as I think it's ready to be merged

**Comment by ethanent** [comment]
Ok, a fix has been made upstream at Centra. https://github.com/ethanent/centra/commit/e063844f99842815ffdc1f2e654d63616a73ba54

The test case proposed was implemented here in Phin. Thank you for the suggestion.

**Pull request closed without merging**
